export const styles = {
  container: {
    minHeight: "100vh",
    maxWidth: "100%",
    backgroundColor: "white",
    alignItems: "center",
    marginTop: "-1rem",
  },
  header: {
    textAlign: "center" as const,
    marginBottom: "1rem",
  },
  title: {
    fontWeight: "bold",
    color: "var(--color-primary)",
    marginBottom: "1rem",
  },
  subtitle: {
    color: "var(--color-font-secondary)",
  },

  mainContent: {
    gridColumn: "span 1",
  },
  pdfSection: {
    background: "linear-gradient(to right, var(--color-primary),var(--color-secondary))",
    padding: "1rem",
    borderRadius: "8px",
    marginBottom: "1rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pdfContainer: {
    width: "100%",
    height: "70vh", // Altura fija para evitar overflow
    maxHeight: "70vh",
    minHeight: "40vh",
    display: "flex",
    flexDirection: "column" as const,
    borderRadius: "10px",
    borderColor: "var(--color-primary)",
    borderWidth: "2px",
    borderStyle: "solid",
    backgroundColor: "#4DC2F419",
    overflow: "hidden",
  },
  pdfLeft: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.5rem",
  },
  pdfText: {
    fontWeight: "600",
    color: "#FFFFFF",
  },
  downloadButton: {
    backgroundColor: "#FFFFFF",
    color: "var(--color-font-secondary)",
    padding: "0.75rem 1rem",
    borderRadius: "12px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.5rem",
    cursor: "pointer",
    border: "none",
    fontWeight: "500",
    fontSize: "14px",
    transition: "all 0.3s ease",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
    "&:hover": {
      transform: "translateY(-2px)",
      boxShadow: "0 4px 16px rgba(0, 0, 0, 0.15)",
    },
    "&:active": {
      transform: "translateY(0)",
      boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
    },
  },
  sidebar: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "1.5rem",
    height: "fit-content",
  },
  sidebarCard: {
    backgroundColor: "white",
    borderRadius: "16px",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.08)",
    border: "1px solid #f1f5f9",
    padding: "24px",
    transition: "all 0.3s ease",
  },
  sidebarTitle: {
    fontWeight: "700",
    color: "#1e293b",
    marginBottom: "20px",
    fontSize: "18px",
    letterSpacing: "-0.025em",
  },
  primaryButton: {
    width: "100%",
    backgroundColor: "var(--color-primary)",
    color: "white",
    padding: "14px 20px",
    borderRadius: "12px",
    fontWeight: "600",
    border: "none",
    cursor: "pointer",
    marginBottom: "16px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    transition: "all 0.3s ease",
    fontSize: "15px",
    boxShadow: "0 4px 12px var(--color-primary)",
    "&:hover": {
      transform: "translateY(-2px)",
      boxShadow: "0 6px 20px var(--color-primary)",
    },
    "&:active": {
      transform: "translateY(0)",
    },
  },
  checkboxContainer: {
    display: "flex",
    alignItems: "flex-start",
    gap: "12px",
    fontSize: "14px",
    color: "#475569",
    marginBottom: "20px",
    padding: "16px",
    backgroundColor: "#f8fafc",
    borderRadius: "12px",
    border: "1px solid #e2e8f0",
  },
  checkbox: {
    marginTop: "2px",
    width: "18px",
    height: "18px",
    accentColor: "var(--color-primary)",
    cursor: "pointer",
  },
  secondaryButton: {
    width: "100%",
    border: "2px solid #e2e8f0",
    backgroundColor: "#5A0075",
    color: "#FFFFFF",
    padding: "12px 20px",
    borderRadius: "12px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    transition: "all 0.3s ease",
    fontWeight: "500",
    fontSize: "1rem",
    marginBottom: "1rem",
    "&:hover": {
      borderColor: "var(--color-primary)",
      backgroundColor: "#fef7f0",
      color: "var(--color-primary)",
      transform: "translateY(-1px)",
      boxShadow: "0 4px 12px rgba(0, 0, 0, 0.1)",
    },
    "&:active": {
      transform: "translateY(0)",
    },
  },
  continueButton: {
    width: "100%",
    border: "none",
    color: "white",
    padding: "14px 20px",
    borderRadius: "12px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    transition: "all 0.3s ease",
    fontWeight: "600",
    fontSize: "15px",
    marginBottom: "16px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.15)",
    "&:hover": {
      transform: "translateY(-2px)",
      boxShadow: "0 6px 20px rgba(0, 0, 0, 0.2)",
    },
    "&:active": {
      transform: "translateY(0)",
    },
    "&:disabled": {
      backgroundColor: "#cbd5e1",
      cursor: "not-allowed",
      transform: "none",
      boxShadow: "none",
    },
  },
  helpSection: {
    background: "linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 100%)",
    borderRadius: "16px",
    padding: "24px",
    textAlign: "center" as const,
    border: "1px solid #bae6fd",
    position: "relative" as const,
    overflow: "hidden",
    "&::before": {
      content: '""',
      position: "absolute",
      top: "0",
      left: "0",
      right: "0",
      height: "3px",
      background: "linear-gradient(90deg, #0ea5e9, #3b82f6)",
    },
  },
  helpIcon: {
    width: "40px",
    height: "40px",
    color: "#0ea5e9",
    margin: "0 auto 12px",
    filter: "drop-shadow(0 2px 4px rgba(14, 165, 233, 0.2))",
  },
  helpTitle: {
    fontWeight: "700",
    color: "#0c4a6e",
    marginBottom: "8px",
    fontSize: "16px",
    letterSpacing: "-0.025em",
  },
  helpText: {
    color: "#0369a1",
    fontSize: "14px",
    marginBottom: "16px",
    lineHeight: "1.5",
  },
  helpButton: {
    background: "linear-gradient(135deg, #0ea5e9 0%, #3b82f6 100%)",
    color: "white",
    padding: "10px 20px",
    borderRadius: "10px",
    fontSize: "14px",
    border: "none",
    cursor: "pointer",
    transition: "all 0.3s ease",
    fontWeight: "600",
    boxShadow: "0 4px 12px rgba(59, 130, 246, 0.3)",
    "&:hover": {
      transform: "translateY(-2px)",
      boxShadow: "0 6px 20px rgba(59, 130, 246, 0.4)",
    },
    "&:active": {
      transform: "translateY(0)",
    },
  },
  // Nuevos estilos para el visor PDF
  pdfViewer: {
    width: "100%",
    height: "100%",
    overflow: "auto",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    padding: "1rem",
  },
  pdfNavigation: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "1rem",
    padding: "1rem",
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderTop: "1px solid #e2e8f0",
  },
  navButton: {
    backgroundColor: "var(--color-primary)",
    color: "white",
    border: "none",
    borderRadius: "8px",
    padding: "0.5rem 1rem",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "500",
    transition: "all 0.3s ease",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    "&:hover": {
      backgroundColor: "var(--color-secondary)",
      transform: "translateY(-1px)",
    },
    "&:disabled": {
      backgroundColor: "#cbd5e1",
      cursor: "not-allowed",
      transform: "none",
    },
  },
  pageInfo: {
    fontSize: "14px",
    color: "#475569",
    fontWeight: "500",
    minWidth: "100px",
    textAlign: "center" as const,
  },
};
