export const styles = {
  container: {
    minHeight: "100vh",
    backgroundColor: "#f9fafb",
    padding: "24px",
  },
  maxWidth: {
    maxWidth: "1652px",
    margin: "0 auto",
  },
  header: {
    textAlign: "center" as const,
    marginBottom: "32px",
  },
  title: {
    fontSize: "24px",
    fontWeight: "bold",
    color: "#1f2937",
    marginBottom: "8px",
  },
  subtitle: {
    color: "#6b7280",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: "24px",
    "@media (min-width: 1024px)": {
      gridTemplateColumns: "2fr 1fr",
    },
  },
  mainContent: {
    gridColumn: "span 1",
  },
  pdfSection: {
    backgroundColor: "#334155",
    color: "white",
    padding: "16px",
    borderRadius: "8px",
    marginBottom: "24px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pdfLeft: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  pdfIcon: {
    width: "32px",
    height: "32px",
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: "4px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "14px",
  },
  pdfText: {
    fontWeight: "500",
  },
  downloadButton: {
    backgroundColor: "white",
    color: "#334155",
    padding: "8px 16px",
    borderRadius: "8px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    border: "none",
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
  proposalCard: {
    backgroundColor: "white",
    borderRadius: "8px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    border: "1px solid #e5e7eb",
    padding: "32px",
  },
  proposalHeader: {
    textAlign: "center" as const,
    marginBottom: "32px",
  },
  proposalTitle: {
    fontSize: "20px",
    fontWeight: "bold",
    color: "#ef4444",
    marginBottom: "8px",
  },
  proposalSubtitle: {
    color: "#6b7280",
  },
  section: {
    marginBottom: "32px",
  },
  sectionTitle: {
    fontSize: "18px",
    fontWeight: "600",
    color: "#1f2937",
    marginBottom: "16px",
  },
  sectionText: {
    color: "#6b7280",
    lineHeight: "1.6",
  },
  objectivesList: {
    listStyle: "none",
    padding: 0,
    margin: 0,
  },
  objectiveItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    marginBottom: "8px",
    color: "#6b7280",
  },
  bullet: {
    color: "#ef4444",
    marginTop: "4px",
  },
  investmentSection: {
    borderTop: "1px solid #e5e7eb",
    paddingTop: "24px",
    textAlign: "center" as const,
  },
  investmentAmount: {
    fontSize: "30px",
    fontWeight: "bold",
    color: "#ef4444",
    marginBottom: "8px",
  },
  investmentDetails: {
    color: "#6b7280",
    fontSize: "14px",
  },
  sidebar: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "16px",
  },
  sidebarCard: {
    backgroundColor: "white",
    borderRadius: "8px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    border: "1px solid #e5e7eb",
    padding: "16px",
  },
  sidebarTitle: {
    fontWeight: "600",
    color: "#1f2937",
    marginBottom: "16px",
  },
  primaryButton: {
    width: "100%",
    backgroundColor: "#ef4444",
    color: "white",
    padding: "12px 16px",
    borderRadius: "8px",
    fontWeight: "500",
    border: "none",
    cursor: "pointer",
    marginBottom: "16px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    transition: "background-color 0.2s",
  },
  checkboxContainer: {
    display: "flex",
    alignItems: "flex-start",
    gap: "8px",
    fontSize: "14px",
    color: "#6b7280",
    marginBottom: "16px",
  },
  checkbox: {
    marginTop: "4px",
  },
  secondaryButton: {
    width: "100%",
    border: "1px solid #d1d5db",
    backgroundColor: "white",
    color: "#374151",
    padding: "8px 16px",
    borderRadius: "8px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    transition: "background-color 0.2s",
  },
  helpSection: {
    backgroundColor: "#eff6ff",
    borderRadius: "8px",
    padding: "16px",
    textAlign: "center" as const,
  },
  helpIcon: {
    width: "32px",
    height: "32px",
    color: "#3b82f6",
    margin: "0 auto 8px",
  },
  helpTitle: {
    fontWeight: "600",
    color: "#1e40af",
    marginBottom: "8px",
  },
  helpText: {
    color: "#1d4ed8",
    fontSize: "14px",
    marginBottom: "12px",
  },
  helpButton: {
    backgroundColor: "#3b82f6",
    color: "white",
    padding: "8px 16px",
    borderRadius: "8px",
    fontSize: "14px",
    border: "none",
    cursor: "pointer",
    transition: "background-color 0.2s",
  },
};
