export const MOCK_ANSWERS_ES: string[] = [
  "Dulce Tandil",
  "Estoy en Argentina y quiero posicionarme en el mercado local de pastelería artesanal, especialmente en pedidos personalizados para eventos chicos y regalos.",
  "Español (rioplatense).",
  "Soy Sofía Ramírez, tengo 26 años y soy emprendedora. Tengo un negocio de pastelería artesanal que manejo sola desde mi casa, donde preparo tortas y productos dulces a pedido.",
  "Me gustaría mostrar cómo empecé vendiendo a amigos y familiares, cómo fui aprendiendo sola y cómo transformé una pasión en mi trabajo.",
  "Prefiero no mostrar detalles de mi vida privada, mi familia y temas económicos personales.",
  "Realizo pastelería artesanal personalizada para cumpleaños, aniversarios y regalos, cuidando el sabor, la estética y los detalles.",
  "Les ahorro tiempo y preocupación al resolverles el postre o el regalo con un producto rico, confiable y hecho a medida.",
  "Que tengan una celebración más linda, sin estrés, y que queden bien con sus invitados o con la persona a la que le hacen el regalo.",
  "La atención personalizada, la dedicación en cada pedido y el trato cercano con el cliente.",
  "Personas de 20 a 45 años que viven en Tandil o alrededores, que valoran lo artesanal, buscan calidad y quieren algo especial para un evento o regalo.",
  "Miedo a que no llegue a tiempo, que no sea igual a la foto o que no valga el precio.",
  "Sorprender a alguien, celebrar un momento especial o quedar bien frente a invitados.",
  "Si hago envíos, si puedo personalizar exactamente lo que quieren y el precio.",
  "Pastelerías artesanales locales de Instagram y TikTok, como pequeños emprendimientos de tortas personalizadas.",
  "Tienen buena presencia en redes, fotos profesionales y más constancia en publicaciones.",
  "Soy muy cercana con mis clientes, escucho mucho lo que quieren y cuido muchísimo los detalles.",
  "Cálida, cercana, auténtica, confiable y alegre.",
  "Detrás de escena, procesos de preparación, decoración de tortas, tips de pastelería, organización de pedidos y vida real de emprender.",
  "Siempre me gustó cocinar y hacer cosas dulces, y vi que podía transformar eso en una salida laboral propia.",
  "En etapa de crecimiento, todavía es pequeño pero cada vez tengo más clientes.",
  "Que por ser casero es poco profesional o de menor calidad.",
  "Ordenada, responsable, detallista y comprometida con cada pedido.",
  "Satisfacción, tranquilidad, alegría y ganas de volver a comprar.",
];
