export const questions = [
  {
    id: "Q01",
    type: "simple_text",
    mandatory: true,
    question: "What is the name of your business or project?",
    short_description: "Enter the name of your brand, business, or project.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q02",
    type: "simple_text",
    mandatory: true,
    question: "In which country do you operate and in what language do you want to create content?",
    short_description:
      "Define your main location and the language you will use to communicate your brand. (e.g., Argentina, Spanish)",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q03",
    type: "extended_text",
    mandatory: true,
    question: "Tell us who you are, what you do, and how you present yourself professionally",
    short_description:
      "Include your full name, profession(s), and a brief description of your background or experience.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q04",
    type: "extended_text",
    mandatory: true,
    question: "How did your business or project start?",
    short_description: "Share the origin: what motivated you to begin and in what context it emerged.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q05",
    type: "extended_text",
    mandatory: true,
    question: "What product or service do you offer and what specific problem does it solve?",
    short_description: "Clearly explain what you sell and the specific need it addresses for your customers.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q06",
    type: "extended_text",
    mandatory: true,
    question: "Why do your customers choose you over other options?",
    short_description:
      "Describe your differentiators, advantages, or what you believe makes you unique compared to competitors.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q07",
    type: "extended_text",
    mandatory: true,
    question: "Tell us about the types of customers you have",
    short_description: "Include who they are, what they need, how they think, and what defines them.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q08",
    type: "simple_text",
    mandatory: true,
    question: "What stage is your business currently in?",
    short_description: "Select the stage: idea, launching, early sales, or growth/scaling.",
    options: ["Idea", "Launching", "Selling", "Scaling"],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q09",
    type: "extended_text",
    mandatory: true,
    question: "How do you currently sell your products or services?",
    short_description:
      "Describe your current sales channels (e.g., social media, website, WhatsApp, in-person, marketplaces, etc.).",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
];

export const questionsES = [
  {
    id: "Q01",
    type: "simple_text",
    mandatory: true,
    question: "¿Cómo se llama tu negocio o proyecto actualmente?",
    short_description: "Ingresa el nombre de tu marca, emprendimiento o proyecto.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q02",
    type: "simple_text",
    mandatory: true,
    question: "¿En qué país operás y en qué idioma querés crear contenido?",
    short_description:
      "Define tu ubicación principal y el idioma en el que vas a comunicar tu marca. (Ej: Argentina, Español)",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q03",
    type: "extended_text",
    mandatory: true,
    question: "Contame quién sos, a qué te dedicás y cómo te presentás profesionalmente",
    short_description: "Incluye tu nombre completo, profesión/es y una breve descripción de tu perfil o trayectoria.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q04",
    type: "extended_text",
    mandatory: true,
    question: "¿Contanos cómo nació tu negocio o proyecto?",
    short_description: "Cuenta el origen: qué te motivó a empezar y en qué contexto surgió.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q05",
    type: "extended_text",
    mandatory: true,
    question: "¿Qué producto o servicio ofrecés y qué problema específico resolvés?",
    short_description: "Explica claramente qué vendés y qué necesidad concreta cubre para tus clientes.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q06",
    type: "extended_text",
    mandatory: true,
    question: "¿Por qué tus clientes te eligen a vos en lugar de otras opciones?",
    short_description: "Describe tus diferenciales, ventajas o lo que crees que te hace único frente a la competencia.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q07",
    type: "extended_text",
    mandatory: true,
    question: "Contame sobre los tipos de clientes que tenes",
    short_description: "Incluye quién es, qué necesita, cómo piensa y qué características lo definen.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q08",
    type: "simple_text",
    mandatory: true,
    question: "¿En qué etapa está tu negocio actualmente?",
    short_description: "Selecciona la etapa: idea, lanzamiento, primeras ventas o crecimiento/escalamiento.",
    options: ["Idea", "Lanzando", "Vendiendo", "Escalando"],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q09",
    type: "extended_text",
    mandatory: true,
    question: "¿Cómo vendés hoy tus productos o servicios?",
    short_description:
      "Describe tus canales de venta actuales (ej: redes sociales, web, WhatsApp, presencial, marketplaces, etc.).",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
];

export const answers = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];
