export const questions = [
  {
    id: "Q1",
    type: "simple_text",
    mandatory: true,
    question: "What is your business currently called?",
    short_description: "Enter the current name of your business or project.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q2",
    type: "simple_text",
    mandatory: true,
    question: "Which country are you in and which market do you want to position yourself in?",
    short_description: "Specify your location and the target market you are aiming for.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q3",
    type: "simple_text",
    mandatory: true,
    question: "In which language do you want to generate content for TikTok?",
    short_description: "Indicate the primary language for your content.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q4",
    type: "extended_text",
    mandatory: true,
    question: "Briefly tell me who you are.",
    short_description: "A short bio about yourself and your background.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q5",
    type: "extended_text",
    mandatory: true,
    question: "What part of your personal story would you like to be part of your brand?",
    short_description: "Share aspects of your journey that resonate with your brand values.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q6",
    type: "extended_text",
    mandatory: true,
    question: "Is there anything in your personal or professional life that you do NOT want to show?",
    short_description: "Set boundaries on what should remain private.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q7",
    type: "extended_text",
    mandatory: true,
    question: "Describe your main product or service in 1–2 sentences.",
    short_description: "A concise summary of what you offer.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q8",
    type: "extended_text",
    mandatory: true,
    question: "What real problem do you solve for your customers?",
    short_description: "Identify the core pain point your business addresses.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q9",
    type: "extended_text",
    mandatory: true,
    question: "What concrete result do you want them to achieve by working with you?",
    short_description: "The outcome or transformation your customers can expect.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q10",
    type: "extended_text",
    mandatory: true,
    question: "What makes your business unique or different?",
    short_description: "Your unique selling proposition or differentiator.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q11",
    type: "extended_text",
    mandatory: true,
    question: "Describe your ideal customer.",
    short_description: "Who are they? Demographics, interests, behaviors.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q12",
    type: "extended_text",
    mandatory: true,
    question: "What frustrations, fears, or obstacles do they have before buying from you?",
    short_description: "Understand the barriers your customers face.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q13",
    type: "extended_text",
    mandatory: true,
    question: "What important goal or objective does your customer want to achieve?",
    short_description: "The main aspiration or desire of your target audience.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q14",
    type: "extended_text",
    mandatory: true,
    question: "What objection or doubt do they mention most often before buying?",
    short_description: "Common hesitations that prevent sales.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q15",
    type: "extended_text",
    mandatory: true,
    question: "Mention 1 to 3 accounts, businesses, or creators similar to you.",
    short_description: "Competitors or inspirations in your niche.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q16",
    type: "extended_text",
    mandatory: true,
    question: "What things do they do well that you would like to match or exceed?",
    short_description: "Strengths of others you admire.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q17",
    type: "extended_text",
    mandatory: true,
    question: "In what things are you better or different than them?",
    short_description: "Your competitive advantage.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q18",
    type: "extended_text",
    mandatory: true,
    question: "How do you want your brand to sound and feel?",
    short_description: "Tone of voice and emotional vibe of your brand.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q19",
    type: "extended_text",
    mandatory: true,
    question: "What topics do you want your brand to cover on TikTok?",
    short_description: "Content themes and pillars for social media.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q20",
    type: "extended_text",
    mandatory: true,
    question: "What led you to create this specific product or service?",
    short_description: "The origin story or motivation behind your offer.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q21",
    type: "extended_text",
    mandatory: true,
    question: "What stage is your business currently in?",
    short_description: "E.g., Idea, Launch, Growth, Scaling.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q22",
    type: "extended_text",
    mandatory: true,
    question: "What wrong perception do you NOT want people to have about your business or product?",
    short_description: "Misconceptions to avoid.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q23",
    type: "extended_text",
    mandatory: true,
    question: "How would you describe your way of working?",
    short_description: "Your methodology or work style.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q24",
    type: "extended_text",
    mandatory: true,
    question: "What do you want your customers to feel or experience after using your product or working with you?",
    short_description: "The emotional aftermath or user experience.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q25",
    type: "extended_text",
    mandatory: true,
    question: "How do you NOT want your brand to sound?",
    short_description: "Define the tone you want to avoid.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q26",
    type: "simple_text",
    mandatory: true,
    question: "What is your current profession?",
    short_description: "Tell us what you do today (job/role).",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
];

export const questionsES = [
  {
    id: "Q1",
    type: "simple_text",
    mandatory: true,
    question: "¿Cómo se llama tu negocio actualmente?",
    short_description: "Ingresa el nombre actual de tu negocio o proyecto.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q2",
    type: "simple_text",
    mandatory: true,
    question: "¿En qué país estás y en qué mercado querés posicionarte?",
    short_description: "Indica tu ubicación y el mercado al que apuntas.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q3",
    type: "simple_text",
    mandatory: true,
    question: "¿En qué idioma querés generar contenido para TikTok?",
    short_description: "Define el idioma principal para tu contenido.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q4",
    type: "extended_text",
    mandatory: true,
    question: "Contame brevemente quién sos",
    short_description: "Una breve biografía sobre ti y tu trayectoria.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q5",
    type: "extended_text",
    mandatory: true,
    question: "¿Qué parte de tu historia personal te gustaría que forme parte de tu marca?",
    short_description: "Comparte aspectos de tu historia que resuenen con tu marca.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q6",
    type: "extended_text",
    mandatory: true,
    question: "¿Hay algo de tu vida personal o profesional que NO querés mostrar?",
    short_description: "Establece límites sobre lo que prefieres mantener privado.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q7",
    type: "extended_text",
    mandatory: true,
    question: "Describí en 1–2 frases tu producto o servicio principal",
    short_description: "Un resumen conciso de lo que ofreces.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q8",
    type: "extended_text",
    mandatory: true,
    question: "¿Qué problema real solucionás para tus clientes?",
    short_description: "Identifica el dolor principal que resuelve tu negocio.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q9",
    type: "extended_text",
    mandatory: true,
    question: "¿Qué resultado concreto querés que obtengan al trabajar con vos?",
    short_description: "El resultado o transformación que pueden esperar.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q10",
    type: "extended_text",
    mandatory: true,
    question: "¿Qué hace único o diferente a tu negocio?",
    short_description: "Tu propuesta única de valor o diferenciador.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q11",
    type: "extended_text",
    mandatory: true,
    question: "Describí a tu cliente ideal",
    short_description: "¿Quiénes son? Demografía, intereses, comportamientos.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q12",
    type: "extended_text",
    mandatory: true,
    question: "¿Qué frustraciones, miedos u obstáculos tiene antes de comprarte?",
    short_description: "Entiende las barreras que enfrentan tus clientes.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q13",
    type: "extended_text",
    mandatory: true,
    question: "¿Qué objetivo o meta importante quiere lograr tu cliente?",
    short_description: "La principal aspiración o deseo de tu público.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q14",
    type: "extended_text",
    mandatory: true,
    question: "¿Qué objeción o duda te mencionan más seguido antes de comprar?",
    short_description: "Dudas comunes que frenan la venta.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q15",
    type: "extended_text",
    mandatory: true,
    question: "Mencioná 1 a 3 cuentas, negocios o creadores parecidos a vos",
    short_description: "Competencia o inspiración en tu nicho.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q16",
    type: "extended_text",
    mandatory: true,
    question: "¿Qué cosas ellos hacen bien que te gustaría igualar o superar?",
    short_description: "Fortalezas ajenas que admiras.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q17",
    type: "extended_text",
    mandatory: true,
    question: "¿En qué cosas vos sos mejor o diferente que ellos?",
    short_description: "Tu ventaja competitiva.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q18",
    type: "extended_text",
    mandatory: true,
    question: "¿Cómo querés que tu marca suene y se sienta?",
    short_description: "Tono de voz y vibra emocional de tu marca.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q19",
    type: "extended_text",
    mandatory: true,
    question: "¿Qué temas querés que tu marca trate en TikTok?",
    short_description: "Temas y pilares de contenido para redes.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q20",
    type: "extended_text",
    mandatory: true,
    question: "¿Qué te llevó a crear este producto o servicio específicamente?",
    short_description: "La historia de origen o motivación detrás de tu oferta.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q21",
    type: "extended_text",
    mandatory: true,
    question: "¿En qué etapa está tu negocio actualmente?",
    short_description: "Ej: Idea, Lanzamiento, Crecimiento, Escala.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q22",
    type: "extended_text",
    mandatory: true,
    question: "¿Qué percepción equivocada NO querés que la gente tenga sobre tu negocio o producto?",
    short_description: "Malentendidos a evitar.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q23",
    type: "extended_text",
    mandatory: true,
    question: "¿Cómo describirías tu forma de trabajar?",
    short_description: "Tu metodología o estilo de trabajo.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q24",
    type: "extended_text",
    mandatory: true,
    question: "¿Qué querés que tus clientes sientan o experimenten después de usar tu producto o trabajar con vos?",
    short_description: "El resultado emocional o experiencia de usuario.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q25",
    type: "extended_text",
    mandatory: true,
    question: "¿Cómo NO querés sonar?",
    short_description: "Definí el tono que querés evitar.",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
  {
    id: "Q26",
    type: "simple_text",
    mandatory: true,
    question: "¿Cuál es tu profesión actual?",
    short_description: "Contanos a qué te dedicás hoy (trabajo/rol).",
    options: [""],
    hasConditionalQuestion: false,
    conditionalQuestion: "",
    defaultAnswer: "",
  },
];

export const answers = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];
